---
title: "Publications"
subtitle: A list of publications
sidebar: false
page-layout: full
toc: false
title-block-banner: true
---


### Recent or in press

Stulp, G. (2023). Describing the Dutch Social Networks and Fertility Study and how to process it. *Demographic Research* 49(19), 493-512. https://www.demographic-research.org/articles/volume/49/19 <a href="https://www.demographic-research.org/articles/volume/49/19" target="_blank">**Download**</a> 

***
Stulp, G, Bonnel, T & Barrett, L. (2023). Simulating the evolution of height in the Netherlands in recent history. *The History of the Family* 28(2), 434-456. https://www.tandfonline.com/doi/full/10.1080/1081602X.2023.2192193 <a href="https://www.tandfonline.com/doi/full/10.1080/1081602X.2023.2192193" target="_blank">**Download**</a> 

***
Stulp, G. (2023). FertNet: Process data from the social networks and fertility survey. https://CRAN.R-project.org/package=FertNet.

***
Langener AM, Stulp G, Kas MJ & Bringmann LF (2023). Capturing the Dynamics of the Social Environment Through Experience Sampling Methods, Passive Sensing, and Egocentric Networks: Scoping Review
*JMIR Mental Health*, 10, https://doi.org/10.2196/42646. <a href="https://doi.org/10.2196/42646" target="_blank">**Download**</a>.  

***
Lu, R, Gauthier, AH & Stulp, G. (2023). Fertility preferences in China in the 21st century. *Journal of Population Research*. 40, 8. https://doi.org/10.1007/s12546-023-09303-0. <a href="https://link.springer.com/article/10.1007/s12546-023-09303-0" target="_blank">**Download**</a> 

***
Xu, X, Stulp, G, van den Bosch, A & Gauthier, A (2022). Understanding Narratives from Demographic Survey Data: a Comparative Study with Multiple Neural Topic Models. Published in *conference proceedings of Empirical Methods in Natural Language Processing*. <a href="/pdf/2022_Xu.pdf" target="_blank">**Download**</a>

***
Aoudjan, M, Van Delft, E , Van der Veen, D, Bringmann, L, Stulp, G, Montagne, B. (2023). Crisissignaleringsplan monitoren en visualiseren: in transitie van reactief naar preventief bij borderline persoonlijkheidsstoornissen. *Gedragstherapie* 56, 1, 54 - 74. <please send me an email if you are interested in this paper>

### 2022

Lu, R, Stulp, G & Gauthier, AH (2022). Quantifying the sources of heterogeneity of fertility preferences in China. *China Population and Development Studies*, 6, 127-140. https://link.springer.com/article/10.1007/s42379-022-00110-3 <a href="https://link.springer.com/article/10.1007/s42379-022-00110-3" target="_blank">**Download**</a> 


***
Buijs, V. L., & Stulp, G. (2022). Friends, family, and family friends: Predicting friendships of Dutch women. *Social Networks*, 70, 25-35. https://doi.org/10.1016/j.socnet.2021.10.008. <a href="https://doi.org/10.1016/j.socnet.2021.10.008" target="_blank">**Download**</a> 

***

Stadel, M., & Stulp, G. (2022). Balancing bias and burden in personal network studies. *Social Networks*, 70, 16-24. https://doi.org/10.1016/j.socnet.2021.10.007. <a href="https://doi.org/10.1016/j.socnet.2021.10.007" target="_blank">**Download**</a>

### 2021

Stulp, G & Barrett, L. (2021). Do data from large personal networks support cultural evolutionary ideas about kin and fertility? *Social Sciences* 10(5):177. https://doi.org/10.3390/socsci10050177. <a href="https://doi.org/10.3390/socsci10050177" target="_blank">**Download**</a>

***
Stulp, G. (2021). Collecting large personal networks in a representative sample of Dutch women. *Social Networks* 64: 63-71. https://doi.org/10.1016/j.socnet.2020.07.012. <a href="https://doi.org/10.1016/j.socnet.2020.07.012" target="_blank">**Download**</a>

***
Verweij, RM, Stulp, G, Snieder, H & Mills, MC. (2021). Explaining the Associations of Education and Occupation with Childlessness: The Role of Desires and Expectations to Remain Childless? *Population Review*, 60, 2, 166-194. muse.jhu.edu/article/839240. <a href="https://muse.jhu.edu/article/839240" target="_blank">**Download**</a> 

***
Buunk, AP, Stulp, G, Schaufeli, WB. (2021). Effect of self-reported height on occupational rank among police officers: Especially for women it pays to be tall.  *Evolutionary Psychological Science*, 7, 411-418. https://doi.org/10.1007/s40806-021-00281-1. <a href="https://doi.org/10.1007/s40806-021-00281-1" target="_blank">**Download**</a>  


### 2020
Bringmann, LF, van der Veen, DC, Wichers, M, Riese, H, & Stulp, G. (2020). ESMvis: A tool for visualizing individual Experience Sampling Method (ESM) data. *Quality of Life Research*, 30, 3179-3188. https://doi.org/10.1007/s11136-020-02701-4. <a href="https://doi.org/10.1007/s11136-020-02701-4" target="_blank">**Download**</a>  

***
Verweij, R., Mills, M., Snieder, H., & Stulp, G. (2020). Three facets of planning and postponement of parenthood in the Netherlands. *Demographic Research* 43(23): 659-672. https://doi.org/10.4054/DemRes.2020.43.23. <a href="https://doi.org/10.4054/DemRes.2020.43.23" target="_blank">**Download**</a>  



### 2019
Verweij, R. M., Mills, M. C., Stulp, G., Nolte, I. M., Barban, N., Tropf, F. C., Carrell, D. T., Aston, K. I., Zondervan, K. T., Rahmioglu, N., Dalgaard, M., Skaarup, C., Hayes, M. G., Dunaif, A., Guo, G., & Snieder, H. (2019). Using Polygenic Scores in Social Science Research: Unraveling Childlessness. *Frontiers in Sociology* 4. <a href="https://doi.org/10.3389/fsoc.2019.00074" target="_blank">**Download**</a>  

***
Stulp, G. & Sear, R. (2019). How might life history theory contribute to life course theory? *Advances in Life Course Research* 41: 100281. <a href="/pdf/2019_stulp_sear.pdf" target="_blank">**Download**</a>

***
Hruschka, DJ, Hackman, JV & Stulp, G. (2019). Identifying the limits to socioeconomic influences on human growth. *Economics & Human Biology* 34: 239-251. <a href="/pdf/2018_Hruschka_EHB_Limits.pdf" target="_blank">**Download**</a>

***
Barrett, L & Stulp, G. (2019). *Evolution and human behaviour: helping to make sense of modern life*. Book chapter (pp 203-222) in: *Genes and Behaviour: Beyond Nature-Nurture* (eds D. Hosken, J. Hunt, N. Wedell). Wiley Press. <a href="/pdf/2019_Barrett & Stulp_Modern life.pdf" target="_blank">**Download**</a>

***
Van der Sluis, JK, Van der Steen, S, Stulp, G & Den Hartigh, R. (2019). *Individual dynamics of talented adolescents*. Book chapter (pp 209-222) in *Psychological development in adolescence: Insights from he dynamic systems approach* (S. Kunnen, M. van der Gaag, N. de Ruiter, B. Jeronimus, editors). Routledge. <a href="/pdf/2018_Van_der_Sluis_et_al_Visualizing_Individual_Dynamics.pdf" target="_blank">**Download**</a>

### 2017
Tropf, FC, Lee, SH, Verweij, RM, Stulp, G, van der Most, PJ, de Vlaming, R, Bakshi, A., Briley, DA, Rahal, C, Hellpap, R, Iliadou, AN, Esko, T, Metspalu, A, Medland, SE, Martin, NG, Barban, N, Snieder, H, Robinson, MR & Mills, MC. (2017). Hidden heritability due to heterogeneity across seven populations. *Nature Human Behaviour* 1: 757-765. <a href="/pdf/2017_Tropf_et_al_Nature Human Behaviour_Heritability.pdf" target="_blank">**Download**</a>

***
Stulp, G., Simons, M.J.P., Grasman, S. & Pollet, T.V. (2017). Assortative mating for human height: a meta-analysis. *American Journal of Human Biology* 29(1): e22917. <a href="https://onlinelibrary.wiley.com/doi/abs/10.1002/ajhb.22917" target="_blank">**Download**</a> 

### 2016
Stulp, G., Sear, R., Schaffnit, S.B., Mills, M.C. & Barrett, L. (2016). The reproductive ecology of industrial societies, Part II: the association between wealth and fertility. *Human Nature* 27(4): 445-470. <a href="https://link.springer.com/article/10.1007%2Fs12110-016-9272-9" target="_blank">**Download**</a> 

***
Stulp, G., Sear, R. & Barrett, L. (2016). The reproductive ecology of industrial societies, Part I: why measuring fertility matters. *Human Nature* 27(4): 422-444. <a href="https://link.springer.com/article/10.1007%2Fs12110-016-9269-4" target="_blank">**Download**</a> 

***
Barrett, L. & Stulp, G. (2016). Revolution, Reconciliation, Integration: Is there a way to bring social and biological anthropology together? *Evolutionary Anthropology* 25: 175-182. <a href="/pdf/2016_Barrett&Stulp_Ev_Anth.pdf" target="_blank">**Download**</a> 

***
Stulp, G. & Barrett, L. (2016). Wealth, fertility, and adaptive behaviour in industrial populations. *Philosophical Transactions of the Royal Society B* 371: 20150153. <a href="/pdf/2016_Stulp & Barrett_Phil_Trans_Wealth.pdf" target="_blank">**Download**</a> 

***
Barrett, L. & Stulp, G. (in press). Evolutionary Psychology. *International Encyclopedia of Anthropology*. Wiley Online Library. <a href="/pdf/2016_Barrett & Stulp_Encyclopedia_Evolutionary-Psychology.pdf" target="_blank">**Download**</a> 

***
Stulp, G. & Barrett, L. (2016). Evolutionary perspectives on human height variation. *Biological Reviews* 91(1): 206-234. <a href="/pdf/2016_Stulp&Barrett_BR_Height.pdf" target="_blank">**Download**</a> 

***
Stulp, G., (in press). 'Big Man'. *Encyclopedia of Evolutionary Psychological Science*. Springer International Publishing. <a href="/pdf/2016_Stulp_Encyclopedia of Evolutionary Psychological Science_Big_Man.pdf" target="_blank">**Download**</a> 


### 2015
Pollet, T.V., Stulp, G., Henzi, P. & Barrett, L. (2015). Taking the aggravation out of data aggregation: a conceptual guide to dealing with statistical issues related to the pooling of individual-level observational data. *American Journal of Primatology* 77(7): 727-740. <a href="/pdf/2015_Pollet_et_al_AMJP_Ecological_Fallacy.pdf" target="_blank">**Download**</a> 


***
Tropf, F.C., Stulp, G., Barban, N., Visscher, P.M., Yang, J., Snieder, H. Mills, M.C. (2015). Human fertility, molecular genetics, and natural selection in modern societies. *PLoS ONE* 10(6): e0126821. <a href="http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0126821" target="_blank">**Download**</a> 

***
Barrett, L., Pollet, T.V. & Stulp, G. (2015). Evolved biocultural beings (who invented computers). *Frontiers in Psychology* 6:1047. <a href="https://www.frontiersin.org/articles/10.3389/fpsyg.2015.01047/full" target="_blank">**Download**</a> 

***
Stulp, G., Barrett, L., Tropf, F.C. & Mills, M. (2015). Does natural selection favour taller stature among the tallest people on earth?*Proceedings of the Royal Society B* 282: 20150211. <a href="/pdf/2015_Stulp_et_al_Proceedings_Height_Netherlands.pdf" target="_blank">**Download**</a> 

***
Stulp, G., Pollet, T.V. & Barrett, L. (2015). The not-always-uniquely-predictive power of an evolutionary approach to understanding our not-so-computational nature. *Frontiers in Psychology* 6(419):1-4. <a href="https://www.frontiersin.org/articles/10.3389/fpsyg.2015.00419/full" target="_blank">**Download**</a> 

***
Conway, JR, Noë, N, Stulp, G, & Pollet, TV. Finding your Soulmate: Homosexual and heterosexual age preferences in online dating. *Personal Relationships* 22(4): 666-678. <a href="/pdf/2015_Conway_et_al_PR_Preferences.pdf" target="_blank">**Download**</a> 

***
Stulp, G, Buunk, AP, Verhulst, S & Pollet, TV. (2015). Human height is positively related to interpersonal dominance in dyadic interactions. *PLoS ONE* 10(2): e0117860, <a href="http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0117860" target="_blank">**Download**</a> 

***
Sorokowski, P., Sorokowska, A., Butovskaya, M., Stulp, G., Huanca, T. & Fink, B. (2015). Body height preferences and actual dimorphism in stature between partners in two non-Western societies (Hadza and Tsimane'). *Evolutionary Psychology* 13(2): 455-469. <a href="http://journals.sagepub.com/doi/abs/10.1177/147470491501300209" target="_blank">**Download**</a> 

***
Stulp, G. & Barrett, L. (2015). Fertility Theory: Theory of Life History Evolution. In: James D. Wright (editor-in-chief), *International Encyclopedia of the Social & Behavioral Sciences*, 2nd edition, Vol 9. Oxford: Elsevier. pp. 40-45. <a href="/pdf/2015_Stulp&Barrett_Encyclopedia_LHT.pdf" target="_blank">**Download**</a> 

### 2014
Barrett, L., Pollet, T.V. & Stulp, G. (2014). From computers to cultivation: reconceptualizing evolutionary psychology. *Frontiers in Psychology* 5: 1-14. <a href="https://www.frontiersin.org/articles/10.3389/fpsyg.2014.00867/full" target="_blank">**Download**</a>

***
Buunk, A.P., Stulp, G. & Ormel, J. (2014). Parental social status and intrasexual competitiveness among adolescents. *Evolutionary Psychology* 12(5): 1022-1037. <a href="http://journals.sagepub.com/doi/abs/10.1177/147470491401200511" target="_blank">**Download**</a>

***
Stulp, G. & Barrett, L. (2014). The course (of) (or) history of life? A response to "A life-course approach to fertility". *Demographic Research*. <a href="https://www.demographic-research.org/volumes/vol30/45/letter.htm" target="_blank">**Download**</a>

***
Stulp, G.<sup>\*</sup> , Mills, M., Pollet, T.V. & Barrett, L.<sup>\*</sup> (2014). Non-linear associations between stature and mate choice characteristics for American men and their spouses. *American Journal of Human Biology* 26:530-537. <sup>\*</sup> authors contributed equally. <a href="pdf/2014_Stulp_et_al_AHJB_Nonlinear.pdf" target="_blank">**Download**</a> 

***
Simons, M.J.P., Stulp, G. & Nakagawa, S. (2014). A statistical approach to distinguish telomere elongation from error in longitudinal datasets. *Biogerontology* 15(1): 99-103. <a href="/pdf/2014_Simon_et_al_Biogeront_Telemore.pdf" target="_blank">**Download**</a>  


***
Varella Valentova, J.V., Stulp, G., Třebický, V. & Havlíček, J. (2014). Preferred and actual relative height among homosexual male partners vary with preferred dominance and sex role. *PLoS ONE* 9(1): e86534. <a href="http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0086534" target="_blank">**Download**</a> 

***
Stulp, G. & Barrett, L. (2014). Binomial tests and randomization approaches: the case of US presidential candidate height and election outcomes. In *SAGE Research Methods Cases*. SAGE Publications Ltd. <a href="/pdf/Stulp & Barrett 2014_Method in Action Case Studies.pdf" target="_blank">**Download**</a> 

### 2013
Pollet, T.V., Stulp, G. & Groothuis, A.G.G. (2013). Born to win? Testing the fighting hypothesis in realistic fights: left-handedness in the Ultimate Fighting Championship. *Animal Behaviour* 86(3): 839-843. <a href="/pdf/Pollet et al 2013_Anim Behav_Handedness.pdf" target="_blank">**Download**</a> 

***
Stulp, G., Buunk, A.P., Kurzban, R. & Verhulst, S. (2013). The height of choosiness: mutual mate choice for stature results in sub-optimal pair formation for both sexes. *Animal Behaviour* 86(1): 37-46. <a href="/pdf/Stulp et al 2013_Anim Behav_The height of choosiness.pdf" target="_blank">**Download**</a> 

***
Barrett, L. & Stulp, G. (2013). Four more reasons why ethology matters: Tinbergen and the human sciences. *Human Ethology Bulletin* 28(4): 39-49. <a href="/pdf/2013_Barrett&Stulp_HEB_Tinbergen.pdf" target="_blank">**Download**</a>

***
Barrett, L. & Stulp, G. (2013). Invited Commentary - The pleasures and pitfalls of studying humans from a behavioural ecological perspective. *Behavioral Ecology* 24: 1045-1046. <a href="/pdf/2013_Barrett&Stulp_BE_Pleasures.pdf" target="_blank">**Download**</a> 

***
Cobey, K.D.<sup>\*</sup>, Stulp, G.<sup>\*</sup>, Laan, F., Buunk, A.P. & Pollet, T.V. (2013). Sex differences in risk taking behavior among Dutch cyclists. *Evolutionary Psychology* 11(2): 350-364. <sup>\*</sup> authors contributed equally. <a href="http://journals.sagepub.com/doi/full/10.1177/147470491301100206" target="_blank">**Download**</a> 

***
Pollet, T.V., Pratt, S.E., Edwards, G. & Stulp, G. (2013). The Golden Years: men from the Forbes 400 have much younger wives when remarrying than the general US population. *Letters on Evolutionary Behavioral Science* 4(1): 5-8. <a href="/pdf/Pollet et al 2013_LEBS_Age differences.pdf" target="_blank">**Download**</a> 

***
Stulp, G., Buunk, A.P. & Pollet, T.V. (2013). Women want taller men more than men want shorter women. *Personality and Individual Differences* 54(8): 877-883. (reported to be the second most downloaded article in Social Psychology in 2013 by Elsevier). <a href="/pdf/Stulp et al 2013_PAID_Women want taller men more than men want shorter women.pdf" target="_blank">**Download**</a> 

***
Stulp, G., Buunk, A.P., Pollet, T.V., Nettle, D. & Verhulst, S. (2013). Are human mating preferences with respect to height reflected in actual pairings? *PLoS ONE* 8(1): e54186. <a href="http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0054186" target="_blank">**Download**</a> 

***
Stulp, G., Buunk, A.P., Verhulst, S., & Pollet, T.V. (2013). Tall claims? Sense and nonsense about the importance of height of US presidents. *The Leadership Quarterly* 24(1): 159-171. <a href="/pdf/Stulp et al 2013_TLQ_Presidential height.pdf" target="_blank">**Download**</a> 

### 2012
Stulp, G., Kuijper, B., Buunk, A.P., Pollet, T.V. & Verhulst, S. (2012). Intralocus sexual conflict over human height. *Biology Letters* 8 (6): 976-978. (recommended by the [Faculty of 1000](https://f1000.com/prime/717955034)). <a href="/pdf/2012_Stulp_et_al_Biol Lett_IASC.pdf" target="_blank">**Download**</a> 

***
Stulp, G., Kordsmeyer, T., Buunk, A.P. & Verhulst, S. (2012). Increased aggression during human group contests when competitive ability is more similar. *Biology Letters* 8 (6): 921-923. <a href="/pdf/2012_Stulp_et_al_Biol Lett_Group_ Aggression.pdf" target="_blank">**Download**</a> 

***
Stulp, G., Buunk, A.P., Verhulst, S., & Pollet, T.V. (2012). High and Mighty: height increases authority in professional refereeing. *Evolutionary Psychology* 10 (3): 588-601. <a href="http://journals.sagepub.com/doi/abs/10.1177/147470491201000314" target="_blank">**Download**</a> 

***
Stirrat, M., Stulp, G. & Pollet, T.V. (2012). Bizygomatic width is associated with death by contact violence in a forensic sample: Narrow-faced males are more likely to die from contact violence than wide-faced males. *Evolution and Human Behavior* 33 (5): 551-556. <a href="/pdf/2012_Stirrat_et_al_EHB_Face.pdf" target="_blank">**Download**</a> 

***
Stulp, G., Verhulst, S., Pollet, T.V. & Buunk, A.P. (2012). The effect of female height on reproductive success is negative in Western populations, but more variable in non-Western populations. *American Journal of Human Biology* 24 (4): 486-494. <a href="/pdf/2012_Stulp_et_al_AJHB_Female_Height.pdf" target="_blank">**Download**</a>

***
Stulp, G., Pollet, T.V., Verhulst, S. & Buunk, A.P. (2012). A curvilinear effect of height on reproductive success in human males. *Behavioral Ecology and Sociobiology* 66 (3): 375-384. <a href="https://link.springer.com/article/10.1007/s00265-011-1283-2" target="_blank">**Download**</a>

### 2011 and earlier
Stulp, G., Verhulst, S., Pollet, T.V., Nettle, D. & Buunk, A.P. (2011). Parental height differences predict the need for an emergency Caesarean section. *PLoS ONE* 6 (6): e20497. <a href="http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0020497" target="_blank">**Download**</a>

***
Stulp, G., Emery, N.J., Verhulst, S. & Clayton, N.S. (2009). Western scrub-jays conceal auditory information when competitors can hear but cannot see. *Biology Letters* 5 (5): 583-585. <a href="/pdf/2011_Stulp_et_al_Biol_Lett_Scrub-jays.pdf" target="_blank">**Download**</a>

***
Spenader, J. & Stulp, G. (2007). Antonymy in contrast relations. In:*Proceedings of the Seventh International Workshop on Computational Semantics*, Tilburg, 10-12 January, 2007. <a href="/pdf/2007_Spenader&Stulp_Comp_Sem_Antonymy.pdf" target="_blank">**Download**</a>

