---
title: "Working papers"
subtitle: A list of publications
sidebar: false
page-layout: full
toc: false
title-block-banner: true
---


### Submitted

 
* Stulp, G., Verhagen, M.D., Arpino, B. Research note: a plea for reporting out-of-sample predictive ability. Submitted to Demography. 

* Stulp, G. Describing the Dutch Social Networks and Fertility Study and How to Process it. Accepted at Demographic Research

* Van Tintelen, A. & Stulp, G., Explaining uncertainty in women's fertility preferences. Submitted to Heliyon

* Langener et al. It'ss all about timing: Exploring different temporal resolutions for analyzing digital phenotyping data. Resubmitted to Advances in Methods and Practices in Psychological Science.

* Stulp, G., Xu, X., Top, L., Sivak, L. A data-driven approach towards network effects on fertility. Submitted to Royel Society Open Science
	
* Xu, X. Van den Bosch, A., Gauthier, A., Stulp, G. Measuring the Response Quality of Open-Ended Questions in a Demographic Web Survey using Linguistic Complexity Features. Submitted to GESIS. 

* Langener, AM, Bringman, LF, Kas, MJ, Stulp, G. Predicting mood based on the social environment measured through the experience sampling method, digital phenotyping, and social networks. Submitted to Administration and Policy in Mental Health and Mental Health Services Research

* Stadel, M, Stulp, G. Langener, AM, Elmer, T, van Duijn, MAJ, Bringmann, LF. Feedback About a Person's Social Context - Personal Networks and Daily Social Interactions. Submitted to Administration and Policy in Mental Health and Mental Health Services Research

* Stulp, G., Van Tintelen, A., Granholm, R. & Lippényi, Z. A microsimulation model of fertility shows that preferences cannot explain why highly educated women remain childless more often. Submit to Population Studies

* Testing the combination of Feeling Safe and Peer Counselling against Formulation-Based Cognitive Behavior Therapy to promote Psychological Wellbeing in People with Persecutory Delusions: Study Protocol for a Randomized Controlled Trial (the Feeling Safe-NL Trial).
Authors: Eva Tolmeijer; Felicity Waite; Louise Isham; Laura Bringmann; Robin Timmers; Arjan van den Berg; Hanneke Schuurmans; Anton B. P. Staring; Paul de Bont; Rob van Grunsven; Gert Stulp; Ben Wijnen; Mark van der Gaag; Daniel Freeman; David van den Berg. Submitted to Trials