---
title: Interactief figuur betreffende de tweets van De Jonge Akademie
author: Gert Stulp
date: '2018-05-20'
---



```{r include = FALSE, warning = FALSE, message = FALSE}
library(ggplot2)
library(ggiraph)

dja <- readRDS("dja.rds")
```

```{r dja, echo = FALSE, message = FALSE, warning = FALSE}
a <- ggplot(dja, aes(x = created_at, y = retweet_count + 1)) +
  geom_point_interactive(aes(tooltip = text_red), 
                         colour = "lightblue", alpha = 0.5, size = 2) +
  geom_smooth(se = FALSE, colour = "orange", alpha = 0.5) +
  theme_minimal()  +
  scale_y_continuous(trans = "log2",
                     breaks = c(1, 2, 3, 5, 9, 17, 33, 65, 129, 257, 513),
                     labels = c(0, 1, 2, 4, 8, 16, 32, 64, 128, 256, 512)) +
  labs(x = "Datum", y = "# retweets", 
       title = "Het aantal retweets van \n'@dejongeakademie' over tijd") +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        axis.title = element_text(size = 20),
        axis.text = element_text(size = 15),
        title = element_text(size = 22)) 

ggiraph(code = print(a), width = 1 )
```

*Als men met de muis boven de datapunten hangt, kan men de tweet lezen.* 